apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  releaseName: nginx
  chart:
    spec:
      chart: ./nginx
      version: "21.1.23" # перевірити актуальну версію!
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
      version: "0.1.0"
  values:
    image:
      repository: nginx
      tag: latest
  #   service:
  #     type: NodePort
  #     nodePorts:
  #       http: 30080
