apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: "27.39.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  # values:
  #   image:
  #     repository: nginx
  #     tag: latest
  #   service:
  #     type: NodePort
  #     nodePorts:
  #       http: 30080
