apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/nginx/overlays/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-helm
    namespace: flux-system
  targetNamespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra/prometheus/overlays/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-helm
    namespace: flux-system
  targetNamespace: monitoring
